reset;

printf("Start...\n\n");

model project.mod;

printf("Loaded model...\n\n");

data project.dat;

printf("Loaded data...\n\n");

option solver gurobi;

solve;

printf("Solving...\n\n");


for{k in K}{
	printf(k);	
	printf("\n");
}
	

display profit, x, y, x.rc, co1.dual, co2.dual, co3.dual, co4.dual, co5.dual, co1.slack, co2.slack, co3.slack, co4.slack, co5.slack > project.out;
close project.out;